import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Increase payload limit for base64 image data
  app.use(express.json({ limit: "50mb" }));

  // Initialize Gemini client helper
  let aiClient: GoogleGenAI | null = null;
  function getGeminiClient(): GoogleGenAI | null {
    const rawKey = process.env.GEMINI_API_KEY?.trim();
    if (!aiClient && rawKey && rawKey !== "MY_GEMINI_API_KEY" && rawKey !== "YOUR_GEMINI_API_KEY") {
      try {
        aiClient = new GoogleGenAI({
          apiKey: rawKey,
          httpOptions: {
            headers: {
              "User-Agent": "aistudio-build",
            },
          },
        });
      } catch {
        aiClient = null;
      }
    }
    return aiClient;
  }

  // Health check endpoint
  app.get("/api/health", (_req, res) => {
    res.json({
      status: "ok",
      hasApiKey: Boolean(process.env.GEMINI_API_KEY),
    });
  });

  // AI-assisted background segmentation endpoint
  app.post("/api/ai-remove-bg", async (req, res) => {
    try {
      const { image } = req.body;
      if (!image) {
        return res.status(400).json({ success: false, error: "Image is required" });
      }

      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        return res.json({
          success: false,
          fallback: true,
          error: "GEMINI_API_KEY is not configured",
        });
      }

      const ai = getGeminiClient();
      if (!ai) {
        return res.json({
          success: false,
          fallback: true,
          error: "Could not initialize Gemini client",
        });
      }

      const base64Data = image.replace(/^data:image\/\w+;base64,/, "");
      const mimeTypeMatch = image.match(/^data:(image\/\w+);base64,/);
      const mimeType = mimeTypeMatch ? mimeTypeMatch[1] : "image/png";

      const prompt = `Segment this image precisely. Identify the primary subject/objects in the foreground.
Completely isolate the subject and replace the entire background with a solid, pure uniform green color (#00FF00).
Keep the edges of the subject sharp, clean, and exact. Do NOT add any shadows, gradients, or other elements.
The output MUST be only the original subject on a pure solid bright green backdrop.`;

      console.log("[AI Remove BG] Requesting image segmentation from Gemini model...");
      const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-lite-image",
        contents: {
          parts: [
            {
              inlineData: {
                data: base64Data,
                mimeType: mimeType,
              },
            },
            {
              text: prompt,
            },
          ],
        },
      });

      let imageUrl: string | null = null;
      if (response.candidates && response.candidates[0] && response.candidates[0].content) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            const b64 = part.inlineData.data;
            imageUrl = `data:${part.inlineData.mimeType || "image/png"};base64,${b64}`;
            break;
          }
        }
      }

      if (!imageUrl) {
        return res.json({
          success: false,
          fallback: true,
          error: "No image generated by AI model",
        });
      }

      return res.json({ success: true, imageUrl });
    } catch (error: any) {
      // Gracefully report authentication, quota, or network issues to allow seamless client fallback
      const errorMsg = typeof error?.message === "string" ? error.message : String(error || "");
      const isAuthError =
        errorMsg.includes("401") ||
        errorMsg.includes("UNAUTHENTICATED") ||
        errorMsg.includes("ACCESS_TOKEN_TYPE_UNSUPPORTED") ||
        errorMsg.includes("authentication credentials");

      console.log(
        `[AI Remove BG] Service notice: ${
          isAuthError
            ? "Authentication required or invalid key; engaging smart local segmentation fallback"
            : "AI service unavailable; engaging smart local segmentation fallback"
        }`
      );

      return res.json({
        success: false,
        fallback: true,
        error: isAuthError
          ? "Gemini API key is unauthenticated. Local edge-preserving segmentation applied."
          : "AI service is temporarily unavailable. Local edge-preserving segmentation applied.",
      });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
